# Porta da aplicação
server.port=8081

# Thymeleaf
spring.thymeleaf.cache=false

# Configuração do banco PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Oracle#21c
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# JPA / Hibernate

# (opcional para debug)
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

# Upload de arquivos
spring.web.resources.static-locations=file:uploads/
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

